---
title: "Project Rmd"
output: html_document
date: "2024-10-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Successful make file!!

## Dataset description

I am using a dataset consisting of statistics on each game played at the 2022
FIFA World Cup.

Five things of interest:

1. Do different parts of the world have different play styles that are reflected
in the data? I.e., can we successfully cluster the teams by geographical area?

2. Which variables are most indicative of a team winning a game? Shots on target 
and possession seem obvious, but are there any important variable that may be
surprising?

3. Which offensive tactics come at the greatest defensive cost? Attempting to
 break the opponents defensive line can lead to goals but is often risky. Does
 a risk such as this lead to more goals against as well?
 
 4. What effect do fouls have on the outcome of the game? Fouling an opposing player
 leads to a free kick, but it also stops the attack. What is the expected value
 of this tradeoff?
 
 5. Are elimination games later in the tournament played differently than the
 group stage games? Is this reflected in the data?







